apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextapp
  namespace: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextapp
  template:
    metadata:
      labels:
        app: nextapp
    spec:
      containers:
      - name: nextapp
        image: armanfeili/nextapp:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: http://flaskapp-service.my-app.svc.cluster.local:4000
---
apiVersion: v1
kind: Service
metadata:
  name: nextapp-service
  namespace: my-app
spec:
  type: LoadBalancer
  selector:
    app: nextapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nextapp-hpa
  namespace: my-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nextapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
